/*
 * Copyright 2017-2026 Philip Helger, pgcc@helger.com
 *
 * Copyright 2011 Google Inc. All Rights Reserved.
 * Author: sreeni@google.com (Sreeni Viswanadha)
 *
 * Copyright (c) 2006, Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.helger.pgcc.parser;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

import org.junit.BeforeClass;
import org.junit.Test;

import com.helger.pgcc.context.PGCCContext;

/**
 * Test class for the string and header helpers of {@link JavaCCGlobals}. They decide what the
 * "Generated by:" line of every emitted file looks like and how string literals are escaped into
 * the generated code, and had no test at all before.
 *
 * @author Philip Helger
 */
public final class JavaCCGlobalsTest
{
  private static final File DIR = new File ("target/globals-test");

  @BeforeClass
  public static void beforeClass ()
  {
    DIR.mkdirs ();
    PGCCContext.reset ();
    Options.init ();
  }

  @Test
  public void testAddEscapes ()
  {
    assertEquals ("plain", JavaCCGlobals.addEscapes ("plain"));
    assertEquals ("a\\nb", JavaCCGlobals.addEscapes ("a\nb"));
    assertEquals ("a\\rb", JavaCCGlobals.addEscapes ("a\rb"));
    assertEquals ("a\\tb", JavaCCGlobals.addEscapes ("a\tb"));
    assertEquals ("a\\fb", JavaCCGlobals.addEscapes ("a\fb"));
    assertEquals ("a\\bb", JavaCCGlobals.addEscapes ("a\bb"));
    assertEquals ("a\\\"b", JavaCCGlobals.addEscapes ("a\"b"));
    assertEquals ("a\\'b", JavaCCGlobals.addEscapes ("a'b"));
    assertEquals ("a\\\\b", JavaCCGlobals.addEscapes ("a\\b"));
    // Below space and above the ASCII range becomes a unicode escape
    assertEquals ("\\u0001", JavaCCGlobals.addEscapes (""));
    assertEquals ("\\u20ac", JavaCCGlobals.addEscapes ("€"));
    assertEquals ("", JavaCCGlobals.addEscapes (""));
  }

  @Test
  public void testAddUnicodeEscapes ()
  {
    // Printable ASCII is left alone
    assertEquals ("abc XYZ 019", JavaCCGlobals.addUnicodeEscapes ("abc XYZ 019"));
    // Everything outside it is escaped, so the generated file stays pure ASCII
    assertEquals ("\\u00e4", JavaCCGlobals.addUnicodeEscapes ("ä"));
    assertEquals ("a\\u20acb", JavaCCGlobals.addUnicodeEscapes ("a€b"));
  }

  @Test
  public void testGetIdString ()
  {
    assertEquals ("Generated by: JavaCC: Do not edit this line. Foo.java",
                  JavaCCGlobals.getIdString ("JavaCC", "Foo.java"));
    assertEquals ("Generated by: JJTree&JavaCC: Do not edit this line. Foo.java",
                  JavaCCGlobals.getIdString (List.of ("JJTree", "JavaCC"), "Foo.java"));
  }

  @Test
  public void testGetToolNamesRoundTrip () throws Exception
  {
    // What getIdString writes, getToolNames has to read back - that round trip was broken by the
    // missing trim until issue 45
    for (final List <String> aTools : List.of (List.of ("JavaCC"), List.of ("JJTree", "JavaCC")))
    {
      final File aFile = new File (DIR, "roundtrip.jj");
      final String sHeader = "/*@bgen(jjtree) " + JavaCCGlobals.getIdString (aTools, "roundtrip.jj") + " */\n";
      Files.write (aFile.toPath (), (sHeader + "options {}\n").getBytes (StandardCharsets.UTF_8));

      assertEquals (aTools, JavaCCGlobals.getToolNames (aFile.getAbsolutePath ()));
      for (final String sTool : aTools)
        assertTrue (sTool, JavaCCGlobals.isGeneratedBy (sTool, aFile.getAbsolutePath ()));
      assertFalse (JavaCCGlobals.isGeneratedBy ("SomethingElse", aFile.getAbsolutePath ()));
    }
  }

  @Test
  public void testGetToolNamesOfAnUnmarkedFile () throws Exception
  {
    final File aFile = new File (DIR, "plain.jj");
    Files.write (aFile.toPath (), "options {}\n".getBytes (StandardCharsets.UTF_8));
    assertTrue (JavaCCGlobals.getToolNames (aFile.getAbsolutePath ()).isEmpty ());
    assertFalse (JavaCCGlobals.isGeneratedBy ("JJTree", aFile.getAbsolutePath ()));
  }

  @Test
  public void testGetToolNamesOfAMissingFile ()
  {
    // A missing file has no tool names rather than blowing up
    assertTrue (JavaCCGlobals.getToolNames (new File (DIR, "does-not-exist.jj").getAbsolutePath ()).isEmpty ());
  }
}
