/*
 * Copyright 2017-2026 Philip Helger, pgcc@helger.com
 *
 * Copyright 2011 Google Inc. All Rights Reserved.
 * Author: sreeni@google.com (Sreeni Viswanadha)
 *
 * Copyright (c) 2006, Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.helger.pgcc.selfgen;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.helger.base.state.ESuccess;
import com.helger.io.file.FileOperationManager;
import com.helger.pgcc.jjtree.JJTree;
import com.helger.pgcc.output.java.FilesJava;

/**
 * Regenerate this project's own parsers with the code in this checkout, without going through
 * <code>ph-javacc-maven-plugin</code>.
 * <p>
 * The project is normally generated by a released version of itself (see
 * <code>docs/internals/bootstrapping.md</code>), so a change to the code generation is invisible to
 * the build until it has been released twice. The Maven route around that needs the sibling plugin
 * checkout; this class needs nothing but the classes that were just compiled.
 * <p>
 * Run it with {@link #main(String[])} to write into a directory, or call
 * {@link #regenerateInto(File)} from a test. <code>SelfGenerateFuncTest</code> uses it to compare
 * the result with what the released generator produced, which turns "did my codegen change affect
 * this project's own parser?" into an assertion.
 *
 * @author Philip Helger
 */
public final class SelfGenerate
{
  private static final Logger LOGGER = LoggerFactory.getLogger (SelfGenerate.class);

  /** Mirrors the ph-javacc-maven-plugin configuration in pom.xml */
  private static final String JDK_VERSION = "1.8";
  private static final String JAVA_TEMPLATE_TYPE = "modern";

  private SelfGenerate ()
  {}

  private static void _run (@NonNull final String sWhat, @NonNull final ESuccess eSuccess)
  {
    if (eSuccess.isFailure ())
      throw new IllegalStateException ("Failed to generate " + sWhat);
    LOGGER.info ("Generated " + sWhat);
  }

  /**
   * The output directory of a grammar is decided by the package it declares, exactly like the Maven
   * plugin does it - ConditionParser.jj lives in src/main/javacc but declares
   * com.helger.pgcc.utils.
   *
   * @param aRoot
   *        The generated sources root. May not be <code>null</code>.
   * @param aGrammar
   *        The grammar file to read the package from. May not be <code>null</code>.
   * @return The directory to generate into. Never <code>null</code>.
   * @throws IOException
   *         On IO error
   */
  @NonNull
  private static File _outputDirOf (@NonNull final File aRoot, @NonNull final File aGrammar) throws IOException
  {
    for (final String sLine : Files.readAllLines (aGrammar.toPath (), StandardCharsets.UTF_8))
    {
      final String sTrimmed = sLine.trim ();
      if (sTrimmed.startsWith ("package ") && sTrimmed.endsWith (";"))
      {
        final String sPackage = sTrimmed.substring ("package ".length (), sTrimmed.length () - 1).trim ();
        final File ret = new File (aRoot, sPackage.replace ('.', '/'));
        ret.mkdirs ();
        return ret;
      }
    }
    throw new IllegalStateException ("Found no package declaration in " + aGrammar);
  }

  /**
   * Regenerate every parser of this project into a directory, laid out by package exactly like the
   * Maven plugin lays it out.
   *
   * @param aTargetDir
   *        Where to write. Emptied first. May not be <code>null</code>.
   * @throws IOException
   *         On IO error
   */
  public static void regenerateInto (@NonNull final File aTargetDir) throws IOException
  {
    FileOperationManager.INSTANCE.deleteDirRecursiveIfExisting (aTargetDir);

    // Use this checkout's templates, not the ones inside whatever jar is on the classpath
    FilesJava.setReadFromClassPath (false);
    try
    {
      for (final String sGrammar : new String [] { "JavaCC.jj", "ConditionParser.jj" })
      {
        final File aGrammar = new File ("src/main/javacc", sGrammar);
        _run (sGrammar,
              com.helger.pgcc.parser.Main.mainProgram ("-JDK_VERSION=" + JDK_VERSION,
                                                       "-JAVA_TEMPLATE_TYPE=" + JAVA_TEMPLATE_TYPE,
                                                       "-OUTPUT_DIRECTORY=" +
                                                                          _outputDirOf (aTargetDir, aGrammar).getAbsolutePath (),
                                                       aGrammar.getAbsolutePath ()));
      }

      // JJTree first, then JavaCC over the grammar it produced - that is what the plugin's
      // "jjtree-javacc" goal does
      final File aJJTreeGrammar = new File ("src/main/jjtree", "JJTree.jjt");
      final File aJJTreeDir = _outputDirOf (aTargetDir, aJJTreeGrammar);
      _run ("JJTree.jjt",
            new JJTree ().main (new String [] { "-JDK_VERSION=" + JDK_VERSION,
                                                "-JAVA_TEMPLATE_TYPE=" + JAVA_TEMPLATE_TYPE,
                                                "-OUTPUT_DIRECTORY=" + aJJTreeDir.getAbsolutePath (),
                                                aJJTreeGrammar.getAbsolutePath () }));
      _run ("JJTree.jj",
            com.helger.pgcc.parser.Main.mainProgram ("-JDK_VERSION=" + JDK_VERSION,
                                                     "-JAVA_TEMPLATE_TYPE=" + JAVA_TEMPLATE_TYPE,
                                                     "-OUTPUT_DIRECTORY=" + aJJTreeDir.getAbsolutePath (),
                                                     new File (aJJTreeDir, "JJTree.jj").getAbsolutePath ()));
    }
    finally
    {
      FilesJava.setReadFromClassPath (true);
    }

    _dropWhatIsHandWritten (aTargetDir);
  }

  /**
   * The Maven plugin never overwrites a class that exists as a hand written source - Token.java in
   * this project carries an extra inner class, and the JJTree node classes are real sources. Drop
   * the generated copies so that what is left is exactly the set the plugin contributes.
   *
   * @param aTargetDir
   *        The generated sources root. May not be <code>null</code>.
   * @throws IOException
   *         On IO error
   */
  private static void _dropWhatIsHandWritten (@NonNull final File aTargetDir) throws IOException
  {
    final Path aRoot = aTargetDir.toPath ();
    final List <Path> aToDelete = new ArrayList <> ();
    try (final Stream <Path> aStream = Files.walk (aRoot))
    {
      aStream.filter (Files::isRegularFile).forEach (aFile -> {
        final String sRelative = aRoot.relativize (aFile).toString ();
        if (new File ("src/main/java", sRelative).isFile ())
          aToDelete.add (aFile);
      });
    }
    for (final Path aFile : aToDelete)
    {
      LOGGER.info ("Dropping " + aRoot.relativize (aFile) + " - it exists as a hand written source");
      Files.delete (aFile);
    }
  }

  /**
   * @param args
   *        Optional single argument: the target directory. Defaults to
   *        <code>target/selfgen</code>.
   * @throws IOException
   *         On IO error
   */
  public static void main (@Nullable final String [] args) throws IOException
  {
    final File aTargetDir = new File (args != null && args.length > 0 ? args[0] : "target/selfgen");
    regenerateInto (aTargetDir);
    LOGGER.info ("Regenerated this project's parsers into " + aTargetDir.getAbsolutePath ());
  }
}
