/*
 * Copyright 2017-2026 Philip Helger, pgcc@helger.com
 *
 * Copyright 2011 Google Inc. All Rights Reserved.
 * Author: sreeni@google.com (Sreeni Viswanadha)
 *
 * Copyright (c) 2006, Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.helger.pgcc.selfgen;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import javax.tools.JavaCompiler;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

import org.junit.BeforeClass;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Regenerate this project's own parsers with the code in this checkout and check the result.
 * <p>
 * This is the cheap half of the self hosting loop: it needs no sibling checkout, no Maven profile
 * and no release. It cannot prove that the regenerated parser <em>works</em> - only a real
 * bootstrap can do that, see <code>docs/internals/bootstrapping.md</code> - but it does prove that
 * the current code produces something that compiles, and it says out loud when the parser this
 * project would generate for itself differs from the one it is currently built with.
 *
 * @author Philip Helger
 */
public final class SelfGenerateFuncTest
{
  private static final Logger LOGGER = LoggerFactory.getLogger (SelfGenerateFuncTest.class);
  private static final File OUT_DIR = new File ("target/selfgen");

  @BeforeClass
  public static void beforeClass () throws IOException
  {
    SelfGenerate.regenerateInto (OUT_DIR);
  }

  /**
   * Remove the two lines that differ between any two releases and say nothing about the code
   * generation: the version in the "Generated by" header, and the checksum derived from the file
   * content.
   *
   * @param s
   *        The file content. May not be <code>null</code>.
   * @return The comparable content. Never <code>null</code>.
   */
  private static String _normalize (final String s)
  {
    return s.replaceAll ("Version [0-9][^ ]* \\*/", "Version <version> */")
            .replaceAll ("OriginalChecksum=[0-9a-f]+", "OriginalChecksum=<checksum>");
  }

  private static List <Path> _javaFilesBelow (final File aDir) throws IOException
  {
    try (final Stream <Path> aStream = Files.walk (aDir.toPath ()))
    {
      final List <Path> ret = new ArrayList <> ();
      aStream.filter (Files::isRegularFile).filter (p -> p.toString ().endsWith (".java")).sorted ().forEach (ret::add);
      return ret;
    }
  }

  @Test
  public void testTheRegeneratedSourcesCompile () throws Exception
  {
    final List <Path> aSources = _javaFilesBelow (OUT_DIR);
    assertTrue ("Nothing was regenerated", aSources.size () > 50);

    final File aClassesDir = new File ("target/selfgen-classes");
    aClassesDir.mkdirs ();

    final JavaCompiler aCompiler = ToolProvider.getSystemJavaCompiler ();
    assertNotNull ("A JDK is required", aCompiler);
    try (final StandardJavaFileManager aManager = aCompiler.getStandardFileManager (null, null, StandardCharsets.UTF_8))
    {
      final List <File> aFiles = new ArrayList <> ();
      for (final Path p : aSources)
        aFiles.add (p.toFile ());
      // The generated parsers reference the hand written classes of this project, so the project's
      // own classpath has to be visible
      assertTrue ("The regenerated parsers must compile",
                  aCompiler.getTask (null,
                                     aManager,
                                     null,
                                     List.of ("-d",
                                              aClassesDir.getAbsolutePath (),
                                              "-classpath",
                                              System.getProperty ("java.class.path"),
                                              "-nowarn"),
                                     null,
                                     aManager.getJavaFileObjectsFromFiles (aFiles)).call ().booleanValue ());
    }
  }

  /**
   * Compare what this checkout generates with what the released generator produced into
   * target/generated-sources. A difference is not a failure - it is exactly what happens after a
   * deliberate codegen change - but it has to be visible, because it is the thing that will only
   * reach this project's own build two releases later.
   *
   * @throws IOException
   *         On IO error
   */
  @Test
  public void testDifferencesAgainstTheReleasedGeneratorAreReported () throws IOException
  {
    final File aPluginRoot = new File ("target/generated-sources");
    if (!aPluginRoot.isDirectory ())
    {
      LOGGER.info ("No plugin output to compare against - skipping");
      return;
    }

    // The plugin skips files that already exist as hand written sources, so only compare what both
    // of them produced
    int nSame = 0;
    final List <String> aDifferent = new ArrayList <> ();
    for (final Path aMine : _javaFilesBelow (OUT_DIR))
    {
      final String sRelative = OUT_DIR.toPath ().relativize (aMine).toString ().replace ('\\', '/');
      Path aTheirs = null;
      for (final String sRoot : new String [] { "javacc", "jjtree", "jjtree-javacc" })
      {
        final Path p = new File (aPluginRoot, sRoot + "/" + sRelative).toPath ();
        if (Files.isRegularFile (p))
        {
          aTheirs = p;
          break;
        }
      }
      if (aTheirs == null)
        continue;

      if (_normalize (Files.readString (aMine, StandardCharsets.UTF_8))
                                                                     .equals (_normalize (Files.readString (aTheirs,
                                                                                                            StandardCharsets.UTF_8))))
        nSame++;
      else
        aDifferent.add (sRelative);
    }

    assertTrue ("Expected to find files produced by both routes", nSame + aDifferent.size () > 10);
    LOGGER.info (nSame +
                 " of " +
                 (nSame + aDifferent.size ()) +
                 " files are identical to what the released generator produced");
    for (final String s : aDifferent)
      LOGGER.info ("  differs: " + s);

    // Pinned so that a codegen change shows up here as a failing assertion with the file list,
    // instead of quietly waiting two releases to become visible
    assertEquals ("The parsers this project would generate for itself differ from the ones it is " +
                  "built with. That is expected right after a codegen change - update this " +
                  "expectation together with the golden files. Differing: " + aDifferent,
                  List.of (),
                  aDifferent);
  }
}
