/*
 * Copyright 2017-2026 Philip Helger, pgcc@helger.com
 *
 * Copyright 2011 Google Inc. All Rights Reserved.
 * Author: sreeni@google.com (Sreeni Viswanadha)
 *
 * Copyright (c) 2006, Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.helger.pgcc.parser;

import org.jspecify.annotations.NonNull;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.helger.pgcc.parser.exp.ExpRStringLiteral;

// A simple class to hold the data generated by the tokenizer. This is passed to
// the code generators to produce code.
public class TokenizerData
{
  // Name of the parser as specified in the PARSER_BEGIN/PARSER_END block.
  private String m_sParserName;
  // Decls coming from TOKEN_MGR_DECLS
  private String m_sDecls;
  // A map of <LexState, first char> to a sequence of literals indexed by:
  // ((int0LexicalState << 16 | (int)c)
  // The literals in the list are all guaranteed to start with the char and re
  // sorted by length so that the "longest-match" rule is done trivially by
  // just going through the sequence in the order.
  // Since they are all literals, there is no duplication (JavaCC checks that)
  // and hence if a longer match is matched, no need to check the shorter match.
  private Map <Integer, List <String>> m_aLiteralSequence;
  // A map of list of kind values indexed by ((int0LexicalState << 16 | (int)c)
  // same key as before.
  private Map <Integer, List <Integer>> m_aLiteralKinds;
  // The NFA start state for a given string literal match. We use this to start
  // the NFA if needed after a literal match is completed.
  private Map <Integer, Integer> m_aKindToNfaStartState;
  /** The main NFA, by state index. */
  private final Map <Integer, NfaState> m_aNfa = new HashMap <> ();
  // On match info indexed by the match kind.
  private final Map <Integer, MatchInfo> m_aAllMatches = new HashMap <> ();
  // Initial nfa states indexed by lexical state.
  private Map <Integer, Integer> m_aInitialStates;
  // Kind of the wildcard match (~[]) indexed by lexical state.
  private Map <Integer, Integer> m_aWildcardKind;
  // Name of lexical state - for debugging.
  private String [] m_aLexStateNames;
  // DEFAULT lexical state index.
  private int m_nDefaultLexState;

  /**
   * @return The value of m_sParserName.
   */
  public String getParserName ()
  {
    return m_sParserName;
  }
  public void setParserName (final String sParserName)
  {
    this.m_sParserName = sParserName;
  }
  /**
   * @return The value of m_sDecls.
   */
  public String getDecls ()
  {
    return m_sDecls;
  }
  public void setDecls (final String sDecls)
  {
    this.m_sDecls = sDecls;
  }
  /**
   * @return The value of m_aLiteralSequence.
   */
  public Map <Integer, List <String>> getLiteralSequence ()
  {
    return m_aLiteralSequence;
  }
  public void setLiteralSequence (final Map <Integer, List <String>> aLiteralSequence)
  {
    this.m_aLiteralSequence = aLiteralSequence;
  }
  /**
   * @return The value of m_aLiteralKinds.
   */
  public Map <Integer, List <Integer>> getLiteralKinds ()
  {
    return m_aLiteralKinds;
  }
  public void setLiteralKinds (final Map <Integer, List <Integer>> aLiteralKinds)
  {
    this.m_aLiteralKinds = aLiteralKinds;
  }
  /**
   * @return The value of m_aKindToNfaStartState.
   */
  public Map <Integer, Integer> getKindToNfaStartState ()
  {
    return m_aKindToNfaStartState;
  }
  public void setKindToNfaStartState (final Map <Integer, Integer> aKindToNfaStartState)
  {
    this.m_aKindToNfaStartState = aKindToNfaStartState;
  }
  /**
   * @return The value of m_aNfa.
   */
  public Map <Integer, NfaState> getNfa ()
  {
    return m_aNfa;
  }
  public void addNfaState (final int nIndex,
                           final Set <Character> characters,
                           final Set <Integer> nextStates,
                           final Set <Integer> aCompositeStates,
                           final int nKind)
  {
    final NfaState aNfaState = new NfaState (nIndex, characters, nextStates, aCompositeStates, nKind);
    m_aNfa.put (Integer.valueOf (nIndex), aNfaState);
  }
  /**
   * @return The value of m_aAllMatches.
   */
  public Map <Integer, MatchInfo> getAllMatches ()
  {
    return m_aAllMatches;
  }
  public void updateMatchInfo (@NonNull final Map <Integer, String> aActions,
                               @NonNull final int [] aNewLexStateIndices,
                               @NonNull final long [] aToSkip,
                               @NonNull final long [] aToSpecial,
                               @NonNull final long [] aToMore,
                               @NonNull final long [] aToToken)
  {
    for (int i = 0; i < aNewLexStateIndices.length; i++)
    {
      final int nVectorIndex = i >> 6;
      final long nBits = (1L << (i & 077));
      EMatchType eMatchType = EMatchType.TOKEN;
      if (aToSkip.length > nVectorIndex && (aToSkip[nVectorIndex] & nBits) != 0L)
      {
        eMatchType = EMatchType.SKIP;
      }
      else
        if (aToSpecial.length > nVectorIndex && (aToSpecial[nVectorIndex] & nBits) != 0L)
        {
          eMatchType = EMatchType.SPECIAL_TOKEN;
        }
        else
          if (aToMore.length > nVectorIndex && (aToMore[nVectorIndex] & nBits) != 0L)
          {
            eMatchType = EMatchType.MORE;
          }
          else
          {
            assert (aToToken.length > nVectorIndex && (aToToken[nVectorIndex] & nBits) != 0L);
            eMatchType = EMatchType.TOKEN;
          }
      final MatchInfo aMatchInfo = new MatchInfo (Options.isIgnoreCase () ? null
                                                                         : ExpRStringLiteral.strLit ()
                                                                                            .getAllImages ()[i],
                                                 i,
                                                 eMatchType,
                                                 aNewLexStateIndices[i],
                                                 aActions.get (Integer.valueOf (i)));
      m_aAllMatches.put (Integer.valueOf (i), aMatchInfo);
    }
  }
  /**
   * @return The value of m_aInitialStates.
   */
  public Map <Integer, Integer> getInitialStates ()
  {
    return m_aInitialStates;
  }
  public void setInitialStates (final Map <Integer, Integer> aInitialStates)
  {
    this.m_aInitialStates = aInitialStates;
  }
  /**
   * @return The value of m_aWildcardKind.
   */
  public Map <Integer, Integer> getWildcardKind ()
  {
    return m_aWildcardKind;
  }
  public void setWildcardKind (final Map <Integer, Integer> aWildcardKind)
  {
    this.m_aWildcardKind = aWildcardKind;
  }
  /**
   * @return The value of m_aLexStateNames.
   */
  public String [] getLexStateNames ()
  {
    return m_aLexStateNames;
  }
  public void setLexStateNames (final String [] aLexStateNames)
  {
    this.m_aLexStateNames = aLexStateNames;
  }
  /**
   * @return The value of m_nDefaultLexState.
   */
  public int getDefaultLexState ()
  {
    return m_nDefaultLexState;
  }
  public void setDefaultLexState (final int nDefaultLexState)
  {
    this.m_nDefaultLexState = nDefaultLexState;
  }
  // Class representing NFA state.
  /**
   * One state of the NFA the interpreter walks.
   *
   * @param index
   *        Index of the state.
   * @param characters
   *        The characters this state can move on. May not be <code>null</code>.
   * @param nextStates
   *        The states reachable from here. May not be <code>null</code>.
   * @param compositeStates
   *        The states this one stands for, if it is a composite one. The initial state has to
   *        transition to several states at once so that the NFA tries every possibility. May not
   *        be <code>null</code>.
   * @param kind
   *        The token kind matched here, or {@link Integer#MAX_VALUE} if this is not a final state.
   */
  public record NfaState (int index,
                          Set <Character> characters,
                          Set <Integer> nextStates,
                          Set <Integer> compositeStates,
                          int kind)
  {}
  /** What a matched kind does with the input. */
  public static enum EMatchType
  {
    SKIP,
    SPECIAL_TOKEN,
    MORE,
    TOKEN,
  }
  /**
   * What matching a kind means: which token it is and what it does to the lexical state.
   *
   * @param image
   *        The string literal image if this is a string literal token, <code>null</code>
   *        otherwise.
   * @param kind
   *        The token kind.
   * @param matchType
   *        Whether this produces a token, a skip, a special token or more input.
   * @param newLexState
   *        The lexical state to switch to, or -1 to stay.
   * @param action
   *        The action to run, or <code>null</code> if there is none.
   */
  public record MatchInfo (String image, int kind, EMatchType matchType, int newLexState, String action)
  {}
}
